### ISSUE TITLE
This should probably have been written in Java

### ISSUE THREAD

**Issue by chrusty** [hailocab/ctop#1]
To query JMX directly (without having to use the HTTP bridge)

**Comment by crufter** [comment]
http://nooooooooooooooo.com/

**Comment by BrianGallew** [comment]
Having written a similar tool quite a while back (casstop from https://github.com/llnw/cassandra_tools ), I can tell you that while a native JMX interface is really nice from the perspective of having "easy" connectivity, the fact that JMX requires EVERY PORT to be open to the server from which you are watching performance is a huge PITA in any kind of secure environment.

Also, writing nice CHUI in Java is a lot more painful than in other languages (says the guy who gave up on Java about the time 1.2 was released).
