### ISSUE TITLE
Cluster-wide statistics

### ISSUE THREAD

**Issue by BrianGallew** [hailocab/ctop#2]
Having written a similar tool (only focussed on the entire cluster), I have to ask if you're intending to expand the scope to look at more than just one system?

**Comment by chrusty** [comment]
Hi Brian.

At the moment there is no plan to expand this to a cluster-wide tool. I'm using the metrics-graphite plugin for this on production clusters, and using Grafana (http://grafana.org/) to generate some very good dashboards which give a very good system-wide overview.

CTOP is really just a quick and dirty utility for immediately inspecting an individual node in the cluster.
