### ISSUE TITLE
Changing ctop 

### ISSUE THREAD

**Issue by eyalba** [hailocab/ctop#6]
Hi All,

I am trying to execute ctop and receive the following error:
Can't connect to stats-provider! (127.0.0.1)

I am running Ubuntu 13 and Cassandra version 1.2.19 and my Cassandra server is not listening on 127.0.0.1.
I have performed the steps as mentioned in the "Pre-requisites:" and "Installation (deb):"

```
-- Added the following to cassandra-env.sh
MX4J_ADDRESS="-Dmx4jaddress=127.0.0.1"  
MX4J_PORT="-Dmx4jport=8081"  
JVM_OPTS="$JVM_OPTS $MX4J_ADDRESS"  
JVM_OPTS="$JVM_OPTS $MX4J_PORT"

-- Executed the following  
apt-get install libmx4j-java
dpkg -i ctop_1.3_amd64.deb (after downloading ctop_1.3_amd64.deb from the provided link)
restarted cassandra
```

but it doesn't work and outputs the following: Can't connect to stats-provider! (127.0.0.1)

Any ideas how to get ctop working on my env?

Thanks,

Eyal.

**Comment by nwag** [comment]
Hi Eyal,

I had the same issue before. My system runs on Ubuntu 14 and Cassandra 2.1.13. It seems the `apt-get install libmx4j-java` command is not sufficient in some cases. You can try to download the mx4j-tools.jar from http://mx4j.sourceforge.net/ and add it to the /lib/ direction of the cassandra classpath. After this restart Cassandra.

You can check this on https://wiki.apache.org/cassandra/Operations in the "Monitoring with MX4J" section.

Best wishes,
Nico

**Comment by eyalba** [comment]
Thanks Nico it worked!.
I had to execute ctop with the correct node host ip:
 ctop -cassandraHost="HOST_IP"
